main:
  hostname: domain-aaa.com
  user: rtcamp
  deploy_path: /home/rtcamp/privacy-sandbox-demos
  prev_releases_limit: 7

develop:
  hostname: 49.13.70.42
  user: rtcamp
  deploy_path: /home/rtcamp/privacy-sandbox-demos
  prev_releases_limit: 3
